### ISSUE TITLE
Flashing pre-compiled hex files

### ISSUE THREAD

**Issue by capsulecorplab** [fprime-community/fprime-baremetal-reference#15]
For the Teensy boards, I'm wondering if it's possible to flash a previously compiled hex file without having to run `fprime-util build` to wait for the Teensy window to pop up

**Comment by ethancheez** [comment]
You would still need the Teensyduino GUI to be open, but from there you can select any `.hex` file. If you save a `.hex` file under `build-artifacts/teensy41/BaremetalReference/bin/BaremetalReference.hex` outside of `build-artifacts`, you can re-select that file in the Teensyduino GUI and upload it.

**Comment by capsulecorplab** [comment]
I think I figured it out! Just needed to dig around for where the Teensyduino GUI launcher was located
![Screenshot from 2023-12-13 15-51-35](https://github.com/fprime-community/fprime-baremetal-reference/assets/14095576/f4e95a4d-31ca-48b1-a0bc-da55d0c6036a)
